# Generated by Django 5.1.6 on 2025-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Pulses', 'Pulses')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retailerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baseprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
