# Generated by Django 5.1.6 on 2025-02-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_remove_product_retailerprice_product_farmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commodity',
            field=models.CharField(choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Pulses', 'Pulses')], max_length=100),
        ),
    ]
