# Generated by Django 5.1.6 on 2025-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0006_farmerprofile_farmer_photo_product_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
    ]
