# Generated by Django 5.1.6 on 2025-02-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0008_remove_farmerprofile_farmer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
