# Generated by Django 5.1.6 on 2025-02-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0009_alter_product_baseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
