# Generated by Django 5.1.6 on 2025-02-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_alter_product_commodity'),
        ('Retailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.product'),
        ),
    ]
