# Generated by Django 5.1.6 on 2025-02-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retailer', '0004_retailerprofile_retailer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerprofile',
            name='retailer_photo',
        ),
    ]
